/**
 * Vaerion packaging — vaerion.lock (MS-6, ADR-0016 + Blueprint §5.5/§7.1).
 *
 * The lockfile is the GENERATED, COMMITTED record of resolved digests and
 * fingerprints: the config fingerprint at build time, every declared
 * extension pin, and the digest of the built bundle. It is canonical JSON,
 * deterministic (a fold over the same inputs — never a wall-clock), and
 * never hand-edited: a stale lock is repaired by rebuilding, then the lock
 * diff is reviewed before commit.
 *
 * Verification law (ADR-0016 decision 2): bundle manifest pins must equal
 * the lock pins at import time; a mismatch is a HARD verification failure
 * (E2202/E2205) — the digest-swap defense of Blueprint §9.4.
 */

import { readFile, stat } from "node:fs/promises";
import { join } from "node:path";
import { canonicalJson } from "../kernel/canonical.ts";
import { blake3HexOf } from "../kernel/hash.ts";
import { VaerionError } from "../kernel/errors.ts";
import type { BundleManifest } from "./format.ts";
import type { VaerionConfig } from "../config/config.ts";

export const LOCK_SCHEMA_VERSION = 1;

/** The generated lock document (canonical JSON at the project root). */
export interface VaerionLock {
  lockSchemaVersion: 1;
  project: { name: string };
  /** blake3 of the canonical config JSON the bundle was built from. */
  configFingerprint: string;
  /** The bundle this lock seals: relative path + identity. */
  bundle: {
    /** Project-relative POSIX path of the .vxn artifact. */
    path: string;
    /** blake3 hex of the full bundle bytes. */
    blake3: string;
    /** Bundle size in bytes. */
    size: number;
    /** Entry count (informational; the manifest is authoritative). */
    entries: number;
  };
  /** Extension pins sorted by name (mirrors the manifest pins). */
  extensions: Array<{ name: string; digest: string }>;
}

/** Build the lock document from a built bundle (pure fold; no clock). */
export function lockFromBundle(config: VaerionConfig, configFingerprint: string, bundlePath: string, manifest: BundleManifest, bundleBlake3: string, bundleSize: number): VaerionLock {
  return {
    lockSchemaVersion: LOCK_SCHEMA_VERSION,
    project: { name: config.project.name },
    configFingerprint,
    bundle: {
      path: bundlePath,
      blake3: bundleBlake3,
      size: bundleSize,
      entries: manifest.entries.length,
    },
    extensions: manifest.pins.map((p) => ({ name: p.name, digest: p.digest })),
  };
}

/** Serialize the lock as canonical JSON + newline (deterministic bytes). */
export function serializeLock(lock: VaerionLock): string {
  return canonicalJson(lock) + "\n";
}

/** Parse + validate a lock document (E2205 on shape drift). */
export function parseLock(text: string): VaerionLock {
  let parsed: unknown;
  try {
    parsed = JSON.parse(text);
  } catch {
    throw new VaerionError("E2205", "vaerion.lock is not valid JSON (the lock is generated — rebuild to regenerate it)");
  }
  const l = parsed as Record<string, unknown>;
  const fail: (why: string) => never = (why) => {
    throw new VaerionError("E2205", `vaerion.lock shape violation: ${why}`);
  };
  if (!l || typeof l !== "object" || Array.isArray(l)) fail("must be a mapping");
  if (l.lockSchemaVersion !== LOCK_SCHEMA_VERSION) fail(`lockSchemaVersion must be ${String(LOCK_SCHEMA_VERSION)}`);
  const project = l.project as Record<string, unknown> | undefined;
  if (!project || typeof project.name !== "string") fail("project.name required");
  if (typeof l.configFingerprint !== "string" || !/^[0-9a-f]{64}$/.test(l.configFingerprint)) fail("configFingerprint must be blake3 hex");
  const bundle = l.bundle as Record<string, unknown> | undefined;
  if (!bundle || typeof bundle.path !== "string" || bundle.path.length === 0) fail("bundle.path required");
  if (typeof bundle.blake3 !== "string" || !/^[0-9a-f]{64}$/.test(bundle.blake3)) fail("bundle.blake3 must be blake3 hex");
  if (typeof bundle.size !== "number" || !Number.isSafeInteger(bundle.size) || (bundle.size as number) < 0) fail("bundle.size must be a non-negative integer");
  if (typeof bundle.entries !== "number" || !Number.isSafeInteger(bundle.entries) || (bundle.entries as number) < 0) fail("bundle.entries must be a non-negative integer");
  if (!Array.isArray(l.extensions)) fail("extensions must be an array");
  for (const e of l.extensions as unknown[]) {
    const ext = e as Record<string, unknown>;
    if (!ext || typeof ext.name !== "string" || typeof ext.digest !== "string" || !/^sha256:[0-9a-f]{64}$/.test(ext.digest)) {
      fail("each extensions entry must be {name, digest: \"sha256:<hex>\"}");
    }
  }
  return parsed as VaerionLock;
}

/** Read the lock if present; null when absent (the lock is generated by package build). */
export async function readLock(root: string): Promise<VaerionLock | null> {
  const path = join(root, "vaerion.lock");
  const exists = await stat(path).then(() => true, () => false);
  if (!exists) return null;
  return parseLock(await readFile(path, "utf8"));
}

/** Compare two extension-pin lists (order-insensitive; names are unique). */
export function pinsEqual(a: Array<{ name: string; digest: string }>, b: Array<{ name: string; digest: string }>): boolean {
  if (a.length !== b.length) return false;
  const map = new Map(a.map((p) => [p.name, p.digest]));
  for (const p of b) {
    if (map.get(p.name) !== p.digest) return false;
  }
  return true;
}

/** The lock's own integrity digest (blake3 over its canonical form). */
export async function lockDigest(lock: VaerionLock): Promise<string> {
  return blake3HexOf(canonicalJson(lock));
}
