/**
 * `vae completions <shell>` — shell completion generation (Phase XXII DX).
 *
 * Design law (D-B — one source of truth): every generator renders from the
 * ONE completion model below. The model is pinned against the command
 * registry of record (COMMAND_HELP in vae.ts) by dx-surface.test.ts — a
 * command added to the registry without updating the model fails the suite,
 * and a model entry without a registry entry fails too.
 *
 * Verification honesty: bash is syntax-checked on the generating host
 * (`bash -n`, pinned in the same test). zsh / fish / powershell carry the
 * honest platform marker — their scripts are generated and structurally
 * reviewed, but no zsh/fish/pwsh host exists in the generating environment
 * (UNVERIFIED — ZSH/FISH/POWERSHELL), exactly like the other host-gated
 * packaging channels.
 *
 * The generated header intentionally carries NO version literal — the
 * version of record is never hand-copied into generated text.
 */

import { VaerionError } from "../kernel/errors.ts";

/** The one completion model. `commands` lists every ratified top-level command. */
export const COMPLETION_MODEL: {
  commands: string[];
  subcommands: Record<string, string[]>;
  flags: string[];
} = {
  commands: [
    "init", "run", "resume", "explain", "journal", "doctor", "dev", "serve",
    "package", "provenance", "repo", "ci", "release", "tour", "account", "ai",
    "center", "version", "help", "completions",
  ],
  subcommands: {
    run: ["research", "demo", "model", "agent", "workflow"],
    journal: ["ls", "show", "verify", "recover", "export"],
    package: ["build", "verify"],
    ci: ["validate", "simulate"],
    release: ["readiness"],
    ai: ["ask", "models"],
    repo: ["verify"],
  },
  flags: ["--json", "--plain", "--dry-run", "--help", "--version", "--quiet", "--cwd"],
};

export const SUPPORTED_SHELLS = ["bash", "zsh", "fish", "powershell"] as const;

/** Programmatic access for tests and embedders. */
export function completionCommands(): string[] {
  return [...COMPLETION_MODEL.commands];
}

export function completionScript(shell: string): string {
  switch (shell) {
    case "bash":
      return bashScript();
    case "zsh":
      return zshScript();
    case "fish":
      return fishScript();
    case "powershell":
      return powershellScript();
    default:
      throw new VaerionError("E1600", `unknown shell: ${shell}`, {
        supported: [...SUPPORTED_SHELLS],
      });
  }
}

function header(shell: string, note: string): string {
  return [
    `# vae shell completions (${shell}) — generated by 'vae completions ${shell}'.`,
    "# Source of truth: the completion model in packages/vaerion/src/cli/completions.ts,",
    "# pinned against the command registry (COMMAND_HELP) by dx-surface.test.ts.",
    `# ${note}`,
    "",
  ].join("\n");
}

function bashScript(): string {
  const cmds = COMPLETION_MODEL.commands.join(" ");
  const flags = COMPLETION_MODEL.flags.join(" ");
  const cases = Object.entries(COMPLETION_MODEL.subcommands)
    .map(([c, subs]) => `    ${c}) COMPREPLY=( $(compgen -W "${subs.join(" ")}" -- "$cur") );;`)
    .join("\n");
  const body = [
    "# shellcheck shell=bash",
    "_vae_completions() {",
    "  local cur c1",
    "  COMPREPLY=()",
    '  cur="${COMP_WORDS[COMP_CWORD]}"',
    `  local commands="${cmds}"`,
    `  local flags="${flags}"`,
    '  if [ "$COMP_CWORD" -eq 1 ]; then',
    '    COMPREPLY=( $(compgen -W "$commands $flags" -- "$cur") )',
    "    return 0",
    "  fi",
    '  c1="${COMP_WORDS[1]}"',
    '  case "$c1" in',
    cases,
    '    *) COMPREPLY=( $(compgen -W "$flags" -- "$cur") );;',
    "  esac",
    "  return 0",
    "}",
    "complete -F _vae_completions vae",
    "",
  ].join("\n");
  return header("bash", "Measured: bash -n (syntax) on the generating host. Install: source <(vae completions bash) in ~/.bashrc.") + body;
}

function zshScript(): string {
  const cmds = COMPLETION_MODEL.commands.join(" ");
  const cases = Object.entries(COMPLETION_MODEL.subcommands)
    .map(([c, subs]) => `        ${c}) _values subcommand ${subs.join(" ")} ;;`)
    .join("\n");
  const body = [
    "#compdef vae",
    "_vae() {",
    "  local -a commands",
    `  commands=(${cmds})`,
    "  _arguments -C '1: :->cmds' '*:: :->args'",
    "  case $state in",
    "    cmds) _describe 'command' commands ;;",
    "    args)",
    "      case $words[1] in",
    cases,
    "      esac ;;",
    "  esac",
    "}",
    '_vae "$@"',
    "",
  ].join("\n");
  return header("zsh", "UNVERIFIED — ZSH: generated and structurally reviewed; no zsh host in the generating environment. Install: fpath+=(~/.vae/completions) && autoload -Uz compinit && compinit.") + body;
}

function fishScript(): string {
  const lines: string[] = [];
  lines.push(`complete -c vae -n '__fish_use_subcommand' -a '${COMPLETION_MODEL.commands.join(" ")}'`);
  for (const [c, subs] of Object.entries(COMPLETION_MODEL.subcommands)) {
    lines.push(`complete -c vae -n '__fish_seen_subcommand_from ${c}' -a '${subs.join(" ")}'`);
  }
  const flagDocs: Record<string, string> = {
    "--json": "stable NDJSON output",
    "--plain": "human-readable output",
    "--dry-run": "plan only, nothing written",
    "--help": "show help and exit",
    "--version": "print the engine version",
    "--quiet": "suppress decorative framing",
  };
  for (const f of COMPLETION_MODEL.flags) {
    lines.push(`complete -c vae -l ${f.slice(2)} -d '${flagDocs[f] ?? "global flag"}'`);
  }
  return (
    header("fish", "UNVERIFIED — FISH: generated and structurally reviewed; no fish host in the generating environment. Install into ~/.config/fish/completions/vae.fish.") +
    lines.join("\n") +
    "\n"
  );
}

function powershellScript(): string {
  const cmds = COMPLETION_MODEL.commands.map((c) => `'${c}'`).join(",");
  const flags = COMPLETION_MODEL.flags.map((c) => `'${c}'`).join(",");
  const subs = Object.entries(COMPLETION_MODEL.subcommands)
    .map(([c, list]) => `    ${c} = ${list.map((s) => `'${s}'`).join(",")}`)
    .join("\n");
  const body = [
    "Register-ArgumentCompleter -CommandName vae -ScriptBlock {",
    "  param($wordToComplete, $commandAst, $cursorPosition)",
    `  $commands = ${cmds}`,
    `  $flags = ${flags}`,
    "  $sub = @{",
    subs,
    "  }",
    "  $tokens = @($commandAst.CommandElements | Select-Object -Skip 1 | ForEach-Object { $_.ToString() })",
    "  $list = if ($tokens.Count -eq 0) { $commands + $flags }",
    "          elseif ($sub.ContainsKey($tokens[0])) { $sub[$tokens[0]] }",
    "          else { $flags }",
    '  $list | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {',
    "    [System.Management.Automation.CompletionResult]::new($_)",
    "  }",
    "}",
    "",
  ].join("\n");
  return header("powershell", "UNVERIFIED — POWERSHELL: generated and structurally reviewed; no pwsh host in the generating environment. Dot-source in $PROFILE.") + body;
}
